name: Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEMETRY_RELEASE: stargazer-telegram-${{ github.sha }}
    steps:
      - uses: actions/checkout@master
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: photonquantum/stargazer-telegram
          username: ${{ secrets.PQ_DOCKER_USERNAME }}
          password: ${{ secrets.PQ_DOCKER_PASSWORD }}
          buildargs: TELEMETRY_RELEASE
      - name: Create a Sentry.io release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: suiseicn
          SENTRY_PROJECT: stargazer-telegram
        with:
          version: ${{ env.TELEMETRY_RELEASE }}
          environment: prod
